### ISSUE TITLE
image input for RL training?

### ISSUE THREAD

**Issue by initial-h** [AlignmentResearch/vlmrm#3]
Thanks for this interesting work. Since the paper mentions the method is based on SAC with MLP network, is the input for RL algorithm is image or state? Thanks.

**Comment by Rocamonde** [comment]
Hi! Thanks for the question. The input to the policy network is the state. Using image arrays would normally require convents.

Will close for now, but if you have any other questions, feel free to create a new issue or, alternatively, email me or one of the other authors.

Best
Juan
